Provider azurm and interpolation syntax
Starting from azurerm 2.0.0, it is required to include the "features" in the provider block, failing with the "terraform plan" fails with the error:

Error: "features": required field is not set

The interpolation syntax also changed from Terraform 0.11.